export const PRACTICE_SUBJECTS = ["HTML", "CSS", "Java", "JavaScript", "Python", "SQL"] as const;
export const PRACTICE_DIFFICULTIES = ["Easy", "Medium", "Hard"] as const;

export type PracticeSubject = (typeof PRACTICE_SUBJECTS)[number];
export type PracticeDifficulty = (typeof PRACTICE_DIFFICULTIES)[number];

export type PracticeQuestion = {
  subject: PracticeSubject;
  topic: string;
  difficulty: PracticeDifficulty;
  prompt: string;
  options: string[];
  correct: number;
  hint: string;
  explanation: string;
};

export const practiceQuestions: PracticeQuestion[] = [
  {
    subject: "HTML",
    topic: "Tags",
    difficulty: "Easy",
    prompt: "What does HTML stand for?",
    options: [
      "HyperText Markup Language",
      "HighText Machine Language",
      "Hyperlink and Text Markup Language",
      "Home Tool Markup Language",
    ],
    correct: 0,
    hint: "HTML describes the structure of a web page with markup tags.",
    explanation: "HTML is HyperText Markup Language. It marks up content so browsers can display headings, links, and other structure.",
  },
  {
    subject: "HTML",
    topic: "Tags",
    difficulty: "Easy",
    prompt: "Which tag creates the largest heading?",
    options: ["<h6>", "<head>", "<h1>", "<header>"],
    correct: 2,
    hint: "Heading levels run from 1 (largest) to 6 (smallest).",
    explanation: "<h1> is the top-level heading. Use one main h1 per page and smaller levels for sections.",
  },
  {
    subject: "HTML",
    topic: "Tags",
    difficulty: "Medium",
    prompt: "Which attribute provides alternative text for an image?",
    options: ["title", "src", "alt", "name"],
    correct: 2,
    hint: "Screen readers and broken-image fallbacks use this attribute.",
    explanation: "The alt attribute describes the image. It is required for accessibility when the image is meaningful.",
  },
  {
    subject: "HTML",
    topic: "Forms",
    difficulty: "Medium",
    prompt: "Which element creates a clickable hyperlink?",
    options: ["<link>", "<a>", "<href>", "<nav>"],
    correct: 1,
    hint: "The destination URL is stored in the href attribute.",
    explanation: "<a href=\"...\"> creates a hyperlink. <link> is used in the document head for stylesheets, not page links.",
  },
  {
    subject: "HTML",
    topic: "Semantic HTML",
    difficulty: "Hard",
    prompt: "Which element is the correct HTML5 document type declaration?",
    options: ["<!DOCTYPE html>", "<!DOCTYPE HTML5>", "<doctype html>", "<html5>"],
    correct: 0,
    hint: "HTML5 uses a short doctype with no DTD URL.",
    explanation: "<!DOCTYPE html> tells the browser to use standards mode for HTML5.",
  },
  {
    subject: "HTML",
    topic: "Semantic HTML",
    difficulty: "Hard",
    prompt: "Which tag is the semantic container for the unique main content of a page?",
    options: ["<section>", "<div>", "<main>", "<article>"],
    correct: 2,
    hint: "There should typically be only one of these landmarks per page.",
    explanation: "<main> represents the dominant content. Assistive tech uses it to skip chrome such as nav and footer.",
  },
  {
    subject: "CSS",
    topic: "Selectors",
    difficulty: "Easy",
    prompt: "What does CSS stand for?",
    options: [
      "Computer Style Syntax",
      "Cascading Style Sheets",
      "Creative Styling System",
      "Coded Style Script",
    ],
    correct: 1,
    hint: "Styles cascade from more general rules to more specific ones.",
    explanation: "CSS is Cascading Style Sheets. It controls colors, layout, spacing, and visual presentation.",
  },
  {
    subject: "CSS",
    topic: "Selectors",
    difficulty: "Easy",
    prompt: "How do you select an element with id=\"hero\"?",
    options: [".hero", "#hero", "hero", "*hero"],
    correct: 1,
    hint: "IDs use a hash. Classes use a dot.",
    explanation: "#hero is an ID selector. .hero would select class=\"hero\".",
  },
  {
    subject: "CSS",
    topic: "Box Model",
    difficulty: "Medium",
    prompt: "Which property adds space inside an element's border?",
    options: ["margin", "padding", "gap", "outline"],
    correct: 1,
    hint: "Margin is outside. Padding is inside.",
    explanation: "Padding is the space between content and the border. Margin is the space outside the border.",
  },
  {
    subject: "CSS",
    topic: "Selectors",
    difficulty: "Medium",
    prompt: "Which selector has higher specificity?",
    options: [".card", "div", "#hero", "*"],
    correct: 2,
    hint: "IDs beat classes, and classes beat element names.",
    explanation: "ID selectors (#hero) are more specific than classes (.card), elements (div), or the universal selector.",
  },
  {
    subject: "CSS",
    topic: "Layout",
    difficulty: "Hard",
    prompt: "What is the default value of flex-direction?",
    options: ["column", "row", "row-reverse", "wrap"],
    correct: 1,
    hint: "Flex items sit in a horizontal line unless you change direction.",
    explanation: "The default flex-direction is row, so children are laid out left to right in most languages.",
  },
  {
    subject: "CSS",
    topic: "Layout",
    difficulty: "Hard",
    prompt: "Which position value keeps an element in flow until it reaches a scroll threshold, then sticks?",
    options: ["fixed", "absolute", "sticky", "static"],
    correct: 2,
    hint: "You usually pair this with top, right, bottom, or left.",
    explanation: "position: sticky is relative until a threshold (such as top: 0) and then behaves like fixed within its container.",
  },
  {
    subject: "Java",
    topic: "Basics",
    difficulty: "Easy",
    prompt: "Which method is the standard entry point of a Java application?",
    options: [
      "public void start()",
      "public static void main(String[] args)",
      "public static Main()",
      "void run(String args)",
    ],
    correct: 1,
    hint: "The JVM looks for a static main method that receives a String array.",
    explanation: "public static void main(String[] args) is the entry point the Java Virtual Machine calls when a program starts.",
  },
  {
    subject: "Java",
    topic: "Basics",
    difficulty: "Easy",
    prompt: "Which primitive type stores true or false?",
    options: ["int", "char", "boolean", "String"],
    correct: 2,
    hint: "String is a class, not a primitive.",
    explanation: "boolean is the primitive for true/false. String is an object type.",
  },
  {
    subject: "Java",
    topic: "OOP",
    difficulty: "Medium",
    prompt: "Which keyword makes one class a subclass of another?",
    options: ["implements", "extends", "inherits", "super"],
    correct: 1,
    hint: "Interfaces use a different keyword.",
    explanation: "extends creates a subclass. implements is used for interfaces. super refers to the parent class.",
  },
  {
    subject: "Java",
    topic: "OOP",
    difficulty: "Medium",
    prompt: "Which access modifier is the most restrictive?",
    options: ["public", "protected", "private", "default (package)"],
    correct: 2,
    hint: "Only the same class can see this member.",
    explanation: "private members are visible only inside the declaring class. That is the tightest encapsulation.",
  },
  {
    subject: "Java",
    topic: "Collections",
    difficulty: "Hard",
    prompt: "Which type can grow and shrink at runtime, unlike a fixed-length array?",
    options: ["int[]", "ArrayList", "char[]", "enum"],
    correct: 1,
    hint: "It lives in java.util and stores objects.",
    explanation: "ArrayList is a resizable list. Arrays have a fixed length once created.",
  },
  {
    subject: "Java",
    topic: "OOP",
    difficulty: "Hard",
    prompt: "What is method overloading in Java?",
    options: [
      "Two methods with the same name and same parameter list in one class",
      "Two methods with the same name but different parameter lists in one class",
      "A subclass replacing a parent method",
      "Calling super() from a constructor",
    ],
    correct: 1,
    hint: "Overriding is different: that replaces a parent method.",
    explanation: "Overloading uses the same method name with different parameters. Overriding replaces an inherited method.",
  },
  {
    subject: "JavaScript",
    topic: "Syntax",
    difficulty: "Easy",
    prompt: "Which keyword declares a variable that cannot be reassigned?",
    options: ["var", "let", "const", "static"],
    correct: 2,
    hint: "Use this when the binding should stay the same.",
    explanation: "const creates a binding that cannot be reassigned. let and var can be reassigned.",
  },
  {
    subject: "JavaScript",
    topic: "Syntax",
    difficulty: "Easy",
    prompt: "What does console.log(value) do?",
    options: [
      "Saves value to localStorage",
      "Prints value to the browser or terminal console",
      "Shows an alert popup",
      "Returns value from a function",
    ],
    correct: 1,
    hint: "Developers use this to inspect values while coding.",
    explanation: "console.log writes to the console. It is for debugging, not for on-page UI.",
  },
  {
    subject: "JavaScript",
    topic: "Functions",
    difficulty: "Medium",
    prompt: "What is the difference between == and ===?",
    options: [
      "They are identical",
      "== compares value after type conversion; === compares value and type",
      "=== converts types; == does not",
      "== only works on numbers",
    ],
    correct: 1,
    hint: "Prefer the operator that does not coerce types.",
    explanation: "== uses type coercion. === is strict equality: both value and type must match.",
  },
  {
    subject: "JavaScript",
    topic: "Functions",
    difficulty: "Medium",
    prompt: "Which array method adds an item to the end of an array?",
    options: ["shift()", "unshift()", "pop()", "push()"],
    correct: 3,
    hint: "The opposite of pop() is this method.",
    explanation: "push() appends to the end. pop() removes from the end. unshift() and shift() work at the start.",
  },
  {
    subject: "JavaScript",
    topic: "DOM",
    difficulty: "Hard",
    prompt: "What is a closure in JavaScript?",
    options: [
      "A function that remembers variables from its outer scope",
      "A loop that never ends",
      "A CSS class on a DOM node",
      "A way to close the browser tab",
    ],
    correct: 0,
    hint: "Inner functions can still use outer variables after the outer function has returned.",
    explanation: "A closure is a function bundled with its lexical environment, so it can access outer variables later.",
  },
  {
    subject: "JavaScript",
    topic: "DOM",
    difficulty: "Hard",
    prompt: "Which keyword pauses a function until a Promise settles?",
    options: ["wait", "yield", "await", "defer"],
    correct: 2,
    hint: "It is used inside an async function.",
    explanation: "await pauses an async function until the Promise fulfills or rejects, then continues with the result.",
  },
  {
    subject: "Python",
    topic: "Loops",
    difficulty: "Easy",
    prompt: "What values does range(3) produce in Python?",
    options: ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "3, 2, 1"],
    correct: 1,
    hint: "range(n) starts at 0 and stops before n.",
    explanation: "range(3) yields 0, 1, and 2. The stop value is exclusive.",
  },
  {
    subject: "Python",
    topic: "Loops",
    difficulty: "Medium",
    prompt: "Which loop is best when you know how many times to repeat?",
    options: ["while True", "for item in sequence", "try/except", "switch"],
    correct: 1,
    hint: "Python has no switch statement in older versions; iterate a sequence or range.",
    explanation: "for item in sequence (or range) is the natural counted or collection loop in Python.",
  },
  {
    subject: "Python",
    topic: "Functions",
    difficulty: "Easy",
    prompt: "Which keyword defines a function in Python?",
    options: ["func", "define", "def", "function"],
    correct: 2,
    hint: "It is a three-letter keyword.",
    explanation: "def starts a function definition, followed by the name and a parameter list.",
  },
  {
    subject: "Python",
    topic: "Functions",
    difficulty: "Hard",
    prompt: "What does a Python function return if it has no return statement?",
    options: ["0", "False", "None", "An empty string"],
    correct: 2,
    hint: "Python's null-like singleton is this value.",
    explanation: "Functions without return (or with a bare return) yield None.",
  },
  {
    subject: "SQL",
    topic: "Joins",
    difficulty: "Easy",
    prompt: "What does SELECT * FROM students return?",
    options: [
      "Only student names",
      "All columns from the students table",
      "A count of students",
      "Only the first row",
    ],
    correct: 1,
    hint: "* means every column.",
    explanation: "SELECT * returns all columns for matching rows in that table.",
  },
  {
    subject: "SQL",
    topic: "Joins",
    difficulty: "Medium",
    prompt: "Which JOIN returns only rows that match in both tables?",
    options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"],
    correct: 2,
    hint: "Non-matching rows are dropped.",
    explanation: "INNER JOIN keeps rows with matching keys in both tables.",
  },
  {
    subject: "SQL",
    topic: "Joins",
    difficulty: "Hard",
    prompt: "Which clause filters groups after GROUP BY?",
    options: ["WHERE", "HAVING", "ORDER BY", "LIMIT"],
    correct: 1,
    hint: "WHERE runs before grouping.",
    explanation: "WHERE filters rows before grouping. HAVING filters aggregated groups after GROUP BY.",
  },
];

export function topicsForSubject(subject: PracticeSubject): string[] {
  return [...new Set(practiceQuestions.filter((q) => q.subject === subject).map((q) => q.topic))];
}

export function questionsFor(
  subject: PracticeSubject,
  topic: string,
  difficulty: PracticeDifficulty,
): PracticeQuestion[] {
  const exact = practiceQuestions.filter(
    (q) => q.subject === subject && q.topic === topic && q.difficulty === difficulty,
  );
  if (exact.length > 0) return exact;
  const sameTopic = practiceQuestions.filter((q) => q.subject === subject && q.topic === topic);
  if (sameTopic.length > 0) return sameTopic;
  return practiceQuestions.filter((q) => q.subject === subject);
}
