export const THS_ORG = {
  name: "Taleem-o-Hunar Society",
  short: "THS",
  tagline: "Education & Skill Development",
  site: "https://www.taleem-o-hunar.com/",
  about: "https://www.taleem-o-hunar.com/about.html",
  contact: "https://www.taleem-o-hunar.com/contact.html",
  landline: "042-36436600",
  landlineHref: "tel:04236436600",
  mobile: "0307-6661880",
  mobileHref: "tel:03076661880",
  email: "muhamad.bilal.anjum@taleemohunar.com",
  maps: "https://maps.app.goo.gl/HioX3dkyoxehmmUq5",
  mailing: [
    "Taleem-o-Hunar Society",
    "Main Jathol Road, Near Bank Alfalah Lake City Meadows",
    "Lahore, Pakistan",
  ],
  headOffice: "Main Jathol Road, Lahore — approximately 1 km from Ring Road Kamahan Exit.",
  subOfficeName: "Jamia Ume Ashraf Jamal",
  subOffice: "Glaxo Town, Ferozepur Road, Lahore.",
  pcp: "2024-1407",
  pcc: "PB-LHR-0430254097041744",
  societiesAct: "RP-12342-L/S/22/949",
  ntn: "6319373",
} as const;
